### ISSUE TITLE
Default zone

### ISSUE THREAD

**Issue by gene-eu-zz** [cossacklabs/acra#40]
Working without zones is actually working with a default zone. We might want to unify the terminology at some point, and streamline the process on AcraServer side.

**Comment by vixentael** [comment]
Makes sense to me, but it doesn't add any user value, except decreasing amount of code to handle zones on your side.

**Comment by 9gunpi** [comment]
This gets fixed by Keyserver in AcraEE and will be addressed differently in CE.
