### ISSUE TITLE
Database convert exiting plaintext records to ciphertext

### ISSUE THREAD

**Issue by Anirudh-MV** [cossacklabs/acra#434]
Hello,

I have got acra-connector and acra-server working and they're working as intended and encrypt and new entry for the columns that I choose.

I now want to convert the existing records of the table to ciphertext. 

What's the simplest way I can convert my database with plaintext records to have ciphertext columns

**Comment by ilammy** [comment]
> What's the simplest way I can convert my database with plaintext records to have ciphertext columns

Well, it depends. Mostly on how much data do you have, how complex is the database schema, how many client IDs you are going to use. Typically, you have several options:

  - Use [**AcraWriter**](https://docs.cossacklabs.com/pages/documentation-acra/#setup-process) to encrypt data locally on a trusted machine.
  - Setup [**AcraTranslator**](https://docs.cossacklabs.com/pages/acratranslator/) to perform encryption for you.
  - Configure [**transparent encryption**](https://docs.cossacklabs.com/pages/documentation-acra/#transparent-proxy-mode) on AcraServer.

#### AcraWriter or AcraTranslator

If you are using AcraWriter or AcraTranslator, the process is something like this:

1. Query the plaintext data to the processing machine.
2. Use AcraWriter or AcraTranslator to encrypt the data.
3. Write back the encrypted data into the database.

This is the most flexible approach as you can choose they keys, client IDs, zones, etc. for each individual datum.

#### Transparent encryption

With transparent encryption, the process looks a bit simpler:

1. Query the plaintext data to the processing machine.
2. Write back *plaintext* data into the database via AcraConnector.

This one is a bit easier to perform from one point of view. The data is encrypted by AcraServer in this case. However, this only moves the complexity to the [transparent encryption configuration](https://docs.cossacklabs.com/pages/documentation-acra/#acraserver-configuration-in-transparent-proxy-mode).

#### What to choose

If you ask me, I'd go with querying the data, encrypting it with AcraWriter, then writing it all back.

Either approach is incremental, so you can gradually encrypt the data, table by table, column by column, row by row, and then immediately check if it can be decrypted back by querying it via AcraConnector.

**Comment by rajatIaxis** [comment]
We have decided to go for the transparent encryption route, as it suites our use case . We are getting some errors.
`ignoring error parsing DDL 'CREATE TABLE cred (userid varchar(20) DEFAULT NULL,password varchar(500)DEFAULT NULL);
INSERT INTO cred(userid,password) VALUES ('uid123','psas1234')': syntax error at position 94 near 'insert'`

php code :
 `<?php

include "./connect.php";
$sql = file_get_contents('backup1.sql');
$conn->multi_query($sql);

$conn->close();`

sql backup : 
`CREATE TABLE cred (userid varchar(20) DEFAULT NULL,password varchar(500)DEFAULT NULL);
INSERT INTO cred(userid,password) VALUES ('uid123','psas1234');`

Thank you,
Regards,
Rajat Kumar Panda

**Comment by Lagovas** [comment]
Actually, you did correctly in the previous version of your message with PHP code) But acra-server doesn't allow multiple queries as one query, so you should split your query and send it 1 by 1. It not mentioned in docs, we will add notes about that.

**Comment by rajatIaxis** [comment]
I edit the comment because I got it working. Can we use any DB migration tools with ACRA?

Regards,
Rajat Kumar Panda

**Comment by ilammy** [comment]
> Can we use any DB migration tools with ACRA?

I'd say "mostly yes, but".

Acra works as an SQL proxy between the client and the database. As long as the migration tool connects over the network and uses SQL, it should be fine to use if you want to encrypt an existing database. However, Acra has limited support of complex queries, prepared statements, it can't process data written by triggers, etc. Make sure that the transfer for the data you want to be encrypted is performed via simple queries, akin to database dumps.

Note that databases usually have special provisions for bulk transfers (e.g., `COPY` in PostgreSQL, `LOAD DATA` in MySQL). Migration tools are usually using them by default. Unfortunately, those **will not work** with Acra's transparent encryption. You'd need to ensure that plain SQL over network connection is used. This might significantly increase the duration of transfer, but it is what it is.

If you want to migrate *already encrypted* data, you can use whatever. As long as the data is transferred intact and Acra's keys are transferred safely, Acra will be able to decrypt it.
