### ISSUE TITLE
Question about Searchable Encryption

### ISSUE THREAD

**Issue by soluzioninformatiche** [cossacklabs/acra#538]
Hi, 

I am looking for a tutorial that's gonna make me test your searchable encryption part of software but the one in the examples is empty and "coming soon".

I have read the provided guide anyway and I cannot find the "encryptor_config_file" in the acra engineering demo. How I do?

Cheers.

**Comment by vixentael** [comment]
Hi @soluzioninformatiche 

searchable encryption only recently became publicly available in Acra CE.

There is no ready-to-use one line example yet. Right now we are working on 0.93 release with type awareness. Open source example with searchable encryption will be added eventually.

Searchable encryption works with examples that transparent encryption – when encryption and decryption happens on AcraServer side.

Here are the docs that explain how searchable encryption works:
https://docs.cossacklabs.com/acra/security-controls/searchable-encryption/

Here is a flag in encryption config that enables searchable encryption for a column:
https://docs.cossacklabs.com/acra/configuring-maintaining/general-configuration/acra-server/encryptor-config/#searchable

I suggest you taking one of the transparent encryption examples, like this one with Django and PostgreSQL
https://github.com/cossacklabs/acra-engineering-demo/#example-1-transparent-encryption-django-postgresql

And edit its encryptor_config file to make "author" field searchable:
https://github.com/cossacklabs/acra-engineering-demo/blob/master/django-transparent/acra-server-configs/encryptor_config.yaml#L19


```
...
  encrypted:
  - column: "author"
    searchable: true
...
```

and then run SELECT queries for author.

**Comment by soluzioninformatiche** [comment]
Here I post the docker's log console file:

time="2022-05-16T16:16:58Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:16:58Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:16:58Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:16:58Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:16:58Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:16:58Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:16:58Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:16:58Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:16:58Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:16:58Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:01Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:17:01Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:17:01Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:17:01Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:17:01Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:17:01Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:17:01Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:17:01Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:17:01Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:01Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:03Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:17:03Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:17:03Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:17:03Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:17:03Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:17:03Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:17:03Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:17:03Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:17:03Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:03Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:05Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:17:05Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:17:05Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:17:05Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:17:05Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:17:05Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:17:05Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:17:05Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:17:05Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:05Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:07Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:17:07Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:17:07Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:17:07Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:17:07Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:17:07Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:17:07Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:17:07Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:17:07Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:07Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:10Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:17:10Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:17:10Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:17:10Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:17:10Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:17:10Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:17:10Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:17:10Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:17:10Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:10Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:13Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:17:13Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:17:13Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:17:13Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:17:13Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:17:13Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:17:13Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:17:13Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:17:13Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:13Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:21Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:17:21Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:17:21Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:17:21Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:17:21Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:17:21Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:17:21Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:17:21Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:17:21Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:21Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:34Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:17:34Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:17:34Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:17:34Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:17:34Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:17:34Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:17:34Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:17:34Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:17:34Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:17:34Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:18:01Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:18:01Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:18:01Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:18:01Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:18:01Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:18:01Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:18:01Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:18:01Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:18:01Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:18:01Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:18:53Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:18:53Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:18:53Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:18:53Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:18:53Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:18:53Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:18:53Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:18:53Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:18:53Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:18:53Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:19:53Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:19:53Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:19:53Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:19:53Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:19:53Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:19:53Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:19:53Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:19:53Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:19:53Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:19:53Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:20:54Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:20:54Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:20:54Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:20:54Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:20:54Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:20:54Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:20:54Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:20:54Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:20:54Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:20:54Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:21:55Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:21:55Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:21:55Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:21:55Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:21:55Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:21:55Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:21:55Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:21:55Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:21:55Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:21:55Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:22:55Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:22:55Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:22:55Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:22:55Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:22:55Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:22:55Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:22:55Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:22:55Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:22:55Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:22:55Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:23:56Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:23:56Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:23:56Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:23:56Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:23:56Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:23:56Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:23:56Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:23:56Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:23:56Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:23:56Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:24:57Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:24:57Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:24:57Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:24:57Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:24:57Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:24:57Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:24:57Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:24:57Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:24:57Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:24:57Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:25:58Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:25:58Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:25:58Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:25:58Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:25:58Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:25:58Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:25:58Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:25:58Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:25:58Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:25:58Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:26:59Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:26:59Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:26:59Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:26:59Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:26:59Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:26:59Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:26:59Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:26:59Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:26:59Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:26:59Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:27:59Z" level=info msg="Starting service acra-server [pid=1]" version=0.92.0

time="2022-05-16T16:27:59Z" level=info msg="Validating service configuration..."

time="2022-05-16T16:27:59Z" level=info msg="Load encryptor configuration from /configs/encryptor_config.yaml ..."

time="2022-05-16T16:27:59Z" level=info msg="Encryptor configuration loaded"

time="2022-05-16T16:27:59Z" level=info msg="Initializing ACRA_MASTER_KEY loader..."

time="2022-05-16T16:27:59Z" level=info msg="Initialized default env ACRA_MASTER_KEY loader"

time="2022-05-16T16:27:59Z" level=info msg="Initialising keystore..."

time="2022-05-16T16:27:59Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:27:59Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"

time="2022-05-16T16:27:59Z" level=error msg="Can't open keyStore" error="keystore folder has an incorrect permissions"

**Comment by Lagovas** [comment]
```
time="2022-05-16T16:27:59Z" level=error msg="Keystore folder has an incorrect permissions -rwxr-xr-x, expected: -rwx------"

time="2022-05-16T16:27:59Z" level=error msg="Can't init keystore" error="keystore folder has an incorrect permissions"
```

imho, it is good enough explanation what went wrong ) run `chmod -R 0600 <keystore folder>` where `<keystore folder>` is path to folder specified in config file or via CLI as `--keys_dir`

**Comment by soluzioninformatiche** [comment]
Since it's all in a docker container how I do have access to that folder?

**Comment by Lagovas** [comment]
It's in local `.acrakeys` folder.
This is [docker-compose file](https://github.com/cossacklabs/acra-engineering-demo/blob/master/django-transparent/docker-compose.django-transparent.yml#L82) that you trying. And there is local .acrakeys folder mounts to docker container. 
So if you run with `run.sh django-transparent` then probably after that script changed you current directory to new temporary folder in `/tmp` and there is should exists `.acrakeys`. Try `ls -a` to find hidden folder. 
And change permissions: `chmod -R 0600 .acrakeys/`. Probably you will need sudo: `sudo chmod -R 0600 .acrakeys/` because in the container all commands running as sudo and owner of that folder will be root.

**Comment by vixentael** [comment]
@soluzioninformatiche we are adding one liner searchable encryption example, please follow #548 and https://github.com/cossacklabs/acra-engineering-demo/pull/53

**Comment by Lagovas** [comment]
> Neither now it's working :c

Sorry, I missed that it requires 0700 instead of 0600: `Keystore folder has an incorrect permissions -rw-------, expected: -rwx------"`
It means that you should execute `chmod -R u+rwx .acrakeys/`.

Plus, I see error `FATAL: password authentication failed for user "root"`. I can guess that yo tried to connect to database directly. You can find credentials to database in same docker-compose file: https://github.com/cossacklabs/acra-engineering-demo/blob/master/django-transparent/docker-compose.django-transparent.yml#L40

There is username is `postgres` and password `test`.
