### ISSUE TITLE
Poison record rotation

### ISSUE THREAD

**Issue by gene-eu-zz** [cossacklabs/acra#55]
Think about this closer to 1.0, talk to users. 

If we do: 

When triggered poison record rotation: 
- acraserver generates new poison records
- user feeds select that triggers poison records
- acra reads output, replaces poison records with old keys with poison records with new keys, generates a dump of inserts.
- user receives sql commands and is able to run it / server runs it for user?

**Comment by vixentael** [comment]
Will plan this feature upon users request.

**Comment by 9gunpi** [comment]
Implemented differently, partially covered in 0.90 key utils, partially by EE Keyserver.
