### ISSUE TITLE
Question about AcraCensor: SQL query without "FROM"

### ISSUE THREAD

**Issue by m8522s** [cossacklabs/acra#666]
Hi team,
I am working on a `acra-censor.yaml` file to whitelist all SQL queries from a webmail app.
My question: How can I write a _pattern_ or _query_ to catch an SQL query that has no _FROM_ part?

The logged SQL query is:
```
time="2023-08-14T18:19:20+02:00" level=error msg="Denied query: 'select vars, ip, changed, now() as ts, case when changed < now() - interval :replaced1 second then :'" code=560 service=acra-censor
```
Thanks for your answer and support.

**Comment by Lagovas** [comment]
Hi. For now, there are no rules/patterns that allow it. Only whitelist of hardcoded [queries](https://docs.cossacklabs.com/acra/security-controls/sql-firewall/queries_filter/). If you have dynamic value in the query then no way to do it now, unfortunately.

**Comment by m8522s** [comment]
Too bad - the query contains a session ID, which is dynamic.
Anyway, thanks for your answer.
