### ISSUE TITLE
Ask: How to use Masking?

### ISSUE THREAD

**Issue by fawwazid** [cossacklabs/acra#690]
Hello Acra,

Is there an example of using Masking for Insert and Select queries in MySQL using only Acra-Server?

Thank you.

**Comment by vixentael** [comment]
@fawwazid Here is a docker-baser Acra engineering example with MySQL and AcraServer that uses masking
https://github.com/cossacklabs/acra-engineering-demo/blob/master/python-mysql-postgresql/README.md

You can see the column "masking" and its configuration setting (symbols to use as mask, where to mask left or right) in the encryption config:
https://github.com/cossacklabs/acra/blob/master/examples/python/extended_encryptor_config.yaml#L20

Docs about masking
https://docs.cossacklabs.com/acra/security-controls/masking/

**Comment by fawwazid** [comment]
Hi @vixentael,

Can Acra Masking use regex patterns?

**Comment by vixentael** [comment]
Acra Community Edition does not support regex for masking, as it's more sophisticated control, but it might be possible for [Acra Enterprise Edition](https://www.cossacklabs.com/acra/).
