### ISSUE TITLE
Request filtering

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/acra#94]
Port Acra request filtering via pre-configured rules file to open-source version.

**Comment by vixentael** [comment]
base logic implemented in #125 

will close this issue preparing to next release

**Comment by vixentael** [comment]
Rules configuration from `yaml` file is implemented in https://github.com/cossacklabs/acra/pull/138

Firewall will be part of the next release.

**Comment by vixentael** [comment]
docs -->
https://github.com/cossacklabs/acra/wiki/acracensor
