### ISSUE TITLE
Different trust levels

### ISSUE THREAD

**Issue by gene-eu** [cossacklabs/acra#98]
**Light**: SSL (instead of SS) and lighter integration.
**Hardcore**: Deeper integration into app runtime and secret protection.

**Comment by vixentael** [comment]
SSL transport between AcraServer and PostreSQL database was covered in [0.76](https://github.com/cossacklabs/acra/releases/tag/0.76) release. 

SSL transport between AcraServer and MySQL database will be part of 0.77 release.
